import type { NextPage } from "next";

import Head from "next/head";
import styles from "../styles/MojePrace.module.css";
import NavBar from "../components/nav-bar";
import Footer from "../components/footer";
import Image from "next/image";

const Home: NextPage = () => {
  const imagesId = [1, 2, 3];
  return (
    <div className={styles.container}>
      <Head>
        <title>Szydełkowy lisek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h1 className="text-5xl font-bold">Tutaj znajdziesz moje prace</h1>
        {imagesId.map((id) => (
          <Image
            src={"/images/szydelko_" + id + ".jpg"}
            alt={"Szydelko " + id}
            height={400}
            width={400}
            key={id}
          ></Image>
        ))}
      </main>
      <Footer></Footer>
    </div>
  );
};

export default Home;
