import type { NextPage } from "next";

import Head from "next/head";
import styles from "../styles/MojePrace.module.css";
import NavBar from "../components/nav-bar";
import Footer from "../components/footer";
import Image from "next/image";

const Home: NextPage = () => {
  const imagesId = [1, 2, 3];
  return (
    <div className={styles.container}>
      <Head>
        <title>Szydełkowy lisek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <h1 className="h-screen text-5xl font-bold snap-start flex justify-center items-center">
          Tutaj znajdziesz moje prace
        </h1>
        {imagesId.map((id) => (
          <div
            className="h-screen w-screen snap-start flex justify-center items-center bg-orange-100"
            key={id}
          >
            <div>
              <Image
                src={"/images/szydelko_" + id + ".jpg"}
                alt={"Szydelko " + id}
                height={600}
                width={600}
                objectFit="contain"
              ></Image>
            </div>
          </div>
        ))}
      </main>
      <Footer></Footer>
    </div>
  );
};

export default Home;
