import type { NextPage } from "next";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/nav-bar";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Szydełkowy lisek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h1 className="text-5xl font-bold">O stronie</h1>
        <p>
          Znajdziesz na tej stronie moje ubrania wykonane na szydełku.
          <br />W przyszłości możliwe, że dodam również kontakt do siebie w celu
          zakupienia dostępnych prac
        </p>
      </main>
      <Footer></Footer>
    </div>
  );
};

export default Home;
